Lesson3 home work anastasia goncear
dgrimaliuc/tekwill-java-project pull request #174
Opened 2024-07-15 15:04 UTC by AnastasiaGoncear

2024-07-15 16:35 UTC, dgrimaliuc requested changes

2024-07-15 16:35 UTC, dgrimaliuc commented on src/main/java/Lesson3AnastasiaGoncear/Scanner.java
> +public class Scanner {
You accidentally created this class as I understand, 
Please remove it

2024-07-15 16:49 UTC, AnastasiaGoncear commented
Please check if the Scanner class is deleted. Still cannot see the current status of my PR.

2024-07-15 17:56 UTC, dgrimaliuc requested changes

2024-07-15 17:56 UTC, dgrimaliuc commented on src/main/java/Lesson3AnastasiaGoncear/ArraysForEach.java
> +    Scanner scanner = new Scanner(System.in);
import scanner

2024-07-15 17:56 UTC, dgrimaliuc requested changes

2024-07-15 17:56 UTC, dgrimaliuc commented on src/main/java/Lesson3AnastasiaGoncear/ArraysForEach.java
> +    scanner.close();
don't need to close it

2024-07-17 13:15 UTC, dgrimaliuc-crunchyroll approved these changes

2024-07-19 15:10 UTC, dgrimaliuc approved these changes

2024-07-19 15:10 UTC, merged