Alexandr samohvalov second java task
dgrimaliuc/tekwill-java-project pull request #22
Opened 2023-06-09 16:03 UTC by LLLAlexandrLL

2023-06-09 19:32 UTC, dgrimaliuc requested changes
Will you create any additiion task?
In task 2 are more points to resolve.

2023-06-09 19:32 UTC, dgrimaliuc commented on SimpleJavaProject/src/main/java/alexandr_samohvalov/NumbersMain.java
> +public class NumbersMain {
why this class is empty?

2023-06-11 19:54 UTC, LLLAlexandrLL commented
New commits added

2023-06-13 18:42 UTC, dgrimaliuc requested changes
Please update your branch, 
pull last changes from master or do rebase.

2023-06-13 18:42 UTC, dgrimaliuc commented on SimpleJavaProject/src/main/java/alexandr_samohvalov/ConditionsMain.java
> +    public static void s(String[] args) {
method name s is incompatible 
method name should dscribe what this method does

2023-06-13 18:42 UTC, dgrimaliuc commented on SimpleJavaProject/src/main/java/alexandr_samohvalov/ConditionsMain.java
> +    public static void maaain(String[] args) {
same

2023-06-13 18:42 UTC, dgrimaliuc commented on SimpleJavaProject/src/main/java/alexandr_samohvalov/NumbersMain.java
> +    public static void ssaww(String[] args) {
same

2023-06-13 18:42 UTC, dgrimaliuc commented on SimpleJavaProject/src/main/java/alexandr_samohvalov/NumbersMain.java
> +    public static void ssaww(String[] args) {
do you need String[] parameter here?

2023-06-13 18:42 UTC, dgrimaliuc commented on SimpleJavaProject/src/main/java/alexandr_samohvalov/ConditionsMain.java
> +    public static void s(String[] args) {
same with paramters

2023-06-13 18:42 UTC, dgrimaliuc commented on SimpleJavaProject/src/main/java/alexandr_samohvalov/NumbersMain.java
> +    public static void maiaafqwn(String[] args) {
same with method name and parameters

2023-06-13 18:42 UTC, dgrimaliuc commented on SimpleJavaProject/src/main/java/alexandr_samohvalov/NumbersMain.java
> +    public static void maaasfin(String[] args) {
please review all methods and fix method name and unused parameter indicated previously

2023-06-13 18:42 UTC, dgrimaliuc commented on SimpleJavaProject/src/main/java/alexandr_samohvalov/StringsMain.java
> +        String txt = "    I hope I am right     ";
try to use  \t instead of multiple spaces

2023-06-20 08:23 UTC, dgrimaliuc requested changes

2023-06-20 08:23 UTC, dgrimaliuc commented on SimpleJavaProject/src/main/java/alexandr_samohvalov/StringsMain.java
> +    public static void ExtractSubStrFromStr(String[] ExtractSubStrFromStr) {
the name of methods should start from lowercase letter
change ExtractSubStrFromStr to extractSubStrFromStr

2023-06-20 08:23 UTC, dgrimaliuc commented on SimpleJavaProject/src/main/java/alexandr_samohvalov/StringsMain.java
> +    public static void ConvertStrUppercase(String[] ConvertStrUppercase) {
same

2023-06-20 08:23 UTC, dgrimaliuc commented on SimpleJavaProject/src/main/java/alexandr_samohvalov/StringsMain.java
> +    public static void StrContainsSpecificSubStr(String[] StrContainsSpecificSubStr) {
same

2023-06-20 08:23 UTC, dgrimaliuc commented on SimpleJavaProject/src/main/java/alexandr_samohvalov/NumbersMain.java
> +    public static void FindMaxNum(String[] FindMaxNum) {
same

2023-06-24 17:44 UTC, dgrimaliuc requested changes
rebase on master and remove SimplJavaProject folder

2023-06-28 10:47 UTC, dgrimaliuc-crunchyroll requested changes
you didn't removed SimpleJavaProject folder

2023-06-28 17:26 UTC, closed without merging