Dmitrii tofan first java track
dgrimaliuc/tekwill-java-project pull request #7
Opened 2023-06-05 09:55 UTC by Dima12A

all done

2023-06-05 18:51 UTC, dgrimaliuc requested changes
Remove idea folder

2023-06-08 08:29 UTC, Dima12A commented
HW_2 - done

2023-06-09 19:57 UTC, dgrimaliuc requested changes
Remove Idea folder

2023-06-09 19:57 UTC, dgrimaliuc requested changes

2023-06-09 19:57 UTC, dgrimaliuc commented on SimpleJavaProject/src/main/java/dmitrii_tofan/ConditionMain.java
> +        if (score >= 90) {
please try it with switch ()

2023-06-09 19:57 UTC, dgrimaliuc commented on SimpleJavaProject/src/main/java/dmitrii_tofan/Main.java
> +package dmitrii_tofan;
In this PR should be only this file!

2023-06-13 18:44 UTC, dgrimaliuc requested changes
Please remove idea folder and
Please update your branch, 
pull last changes from master or do rebase.

2023-07-02 16:14 UTC, closed without merging