eight task Gontari Anna
dgrimaliuc/tekwill-java-project pull request #97
Opened 2023-06-28 19:54 UTC by Gontari-Anna

2023-06-29 07:36 UTC, dgrimaliuc-crunchyroll requested changes

2023-06-29 07:36 UTC, dgrimaliuc-crunchyroll commented on src/main/java/anna_gontari/CopyingFile.java
> +            if (path.mkdir() == true) {
path.mkdir() can be only true or false 

path.mkdir() returns true or false , so the third else is redundant, there is not 3-th case

2023-06-29 07:36 UTC, dgrimaliuc-crunchyroll commented on src/main/java/anna_gontari/files/MyFile.txt
> +Welcome to the file
don't need to commit files as they will not be in use

2023-07-02 16:11 UTC, dgrimaliuc requested changes

2023-07-02 16:11 UTC, dgrimaliuc commented on src/main/java/anna_gontari/CopyingFile.java
> +            if (path.mkdir() == true) {
make it easier 
if (path.mkdir())

2023-07-02 16:11 UTC, dgrimaliuc commented on src/main/java/anna_gontari/CopyingFile.java
> +            } else if (path.mkdir() == false) {
make it easier 
just else

2023-07-04 18:21 UTC, dgrimaliuc approved these changes

2023-07-04 18:22 UTC, merged